name: vortex
description: "Vortex is a first powerful Flutter framework that brings the convenience and structure of Nuxt.js to Flutter development."
version: 0.0.2
repository: https://github.com/vortex-flutter/vortex/tree/main
issue_tracker: https://github.com/vortex-flutter/vortex/issues
homepage: https://vortex.brighthustle.in
documentation: https://flutterwind.dev/getting-started
topics: [vortex, nuxt, flutter, build-system]
funding: [https://github.com/sponsors/vortex-flutter]

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  args: ^2.7.0
  flutter:
    sdk: flutter
  logger: ^2.5.0
  meta: ^1.16.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
